version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  my-go-app:
    build: .
    restart: always
    ports:
      - "${Docker_Port}:${Docker_Port}"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
